### ISSUE TITLE
如何获取proto内容？

### ISSUE THREAD

**Issue by daniel-chang-pvt** [XiaoMiku01/douyin-live-go#7]
我用playwright-go库写了一个获取抖音弹幕的工具，使用了您的proto文件，可以使用。
我想请问下，您是如何知道proto里面的内容的。我通过一些逆向去查看proto结构，只能看到大概，没办法看到像您的proto里面内容如此详细。如何去分析获取到的二进制数据，逆向出proto结构？

**Comment by XiaoMiku01** [comment]
不是逆二进制 逆js
